### ISSUE TITLE
좋아요 도메인, CRUD 기능 구현

### ISSUE THREAD

**Issue by skatn** [korean-brains/online-butler-back#4]
## Description
사용자가 마음에 든 게시물을 좋아요 기능을 통해 스크랩 할 수 있다.

## Todo
- [x] 좋아요 Entity 클래스 작성
- [x] 좋아요 CRUD 기능 구현
- [x] 좋아요한 게시글 조회

## ETC
- 같은 게시물을 중복하여 좋아요 기능을 사용할 수 없다.
- 게시글이 삭제되도 좋아요 목록에서 사라지지 않는다.
