### ISSUE TITLE
게시글 조회 API 응답 데이터 필드 변경

### ISSUE THREAD

**Issue by skatn** [korean-brains/online-butler-back#41]
## Description
게시글 조회 API의 응답 데이터의 구조를 다음과 같이 변경한다.

```
{
    id: 1,
    createdAt: '2024-02-04T18:00:00',
    caption:
      '게시글 내용',
    images: ['/images/cat.jpg', '/images/cat.jpg'],
    likeCount: 1200,
    commentCount: 10,
    writer: {
      id: 1,
      profile: '/images/profile.jpg',
      name: '닉네임',
      followed: false,
    },
    tags: [
      { id: 1, name: '고양이' },
      { id: 2, name: '뚱냥이' },
    ],
  }
```

## Todo
- [x] 게시글 단건 조회 API 응답 데이터 구조 변경
- [x] 게시글 목록 조회 API 응답 데이터 구조 변경
- [x] 좋아요한 게시글 목록 조회 API 응답 데이터 구조 변경
